dist: bionic

language: cpp

addons:
  apt:
    update: true
    packages:
      - cmake
      - libtool
      - autoconf
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libncurses5-dev
      - libglm-dev
      - libboost-all-dev
      - libasound2-dev
      - libjack-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      script:
          - make
    - os: windows
      script:
        - choco install innounp grep
        - set -e
        - ./make.bat
