dist: xenial

language: cpp

addons:
  apt:
    update: true
    packages:
      - cmake
      - libtool
      - autoconf
      - g++-4.8
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libncurses5-dev
      - libglm-dev
      - libboost-all-dev
      - gnugo

matrix:
  exclude:
    - os: linux
      compiler: gcc-4.8
      script:
          - make
  include:
    - os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - make.bat
